services:
  - type: web
    name: arps-roblox-portfolio
    env: static
    buildCommand: echo "No build required - static site"
    staticPublishPath: .
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=86400
      - path: /*.html
        name: Cache-Control
        value: public, max-age=3600
      - path: /*.css
        name: Cache-Control
        value: public, max-age=31536000
      - path: /*.js
        name: Cache-Control
        value: public, max-age=31536000
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
